version: "3.8"

services:
  database:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    networks:
      - static-asset-manager-network

networks:
  static-asset-manager-network:
